// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int32         `json:"id"`
	Email     string        `json:"email"`
	Username  string        `json:"username"`
	FullName  string        `json:"full_name"`
	Age       sql.NullInt32 `json:"age"`
	IsActive  sql.NullBool  `json:"is_active"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}
