// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	// queries.sql (for sqlc)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int32) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUsersByAgeRange(ctx context.Context, arg GetUsersByAgeRangeParams) ([]User, error)
	ListActiveUsers(ctx context.Context) ([]User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SearchUsersByName(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserActiveStatus(ctx context.Context, arg UpdateUserActiveStatusParams) error
}

var _ Querier = (*Queries)(nil)
